version: "3.8"

services:
  # api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:postgrespassword@db:5432/leap?schema=public"

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: leap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

  # adminer:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - "db"
  #   ports:
  #     - 9900:8080

  # minio:
  #   image: minio/minio
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - ./storage:/data
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: miniopassword
  #   command: server --console-address ":9001" /data
