name: app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.8
  encrypt_shared_preferences: ^0.3.8
  flutter:
    sdk: flutter
  get: 4.6.6
  responsive_builder: 0.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
