### get root

GET http://localhost:8080

### signin

POST http://localhost:8080/auth  
Content-Type: application/json

{
    "username":"bob@example.com",
    "password":"password"
}

### signup

POST http://localhost:8080/signup
Content-Type: application/json

{
    "name" : "bob",
    "username":"bob@example.com",
    "password":"password" 
}

### show profile

GET http://localhost:8080/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJib2JAZXhhbXBsZS5jb20iLCJpYXQiOjE2OTU4Mjc3NTIsImV4cCI6MTY5NjQzMjU1Mn0.pfc0k-3hRaQGZ4sR4Rm0NkUqArrdYI18j6biYVBsjV0

### get user devices

GET http://localhost:8080/devices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJib2JAZXhhbXBsZS5jb20iLCJpYXQiOjE2OTU5NDc5OTcsImV4cCI6MTY5NjU1Mjc5N30.2OF74as3PMJxVoqia52M1cp-XrU59e1RoG-TL7AXz9U

### get user firmware

GET http://localhost:8080/firmwares
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJib2JAZXhhbXBsZS5jb20iLCJpYXQiOjE2OTU5NDc5OTcsImV4cCI6MTY5NjU1Mjc5N30.2OF74as3PMJxVoqia52M1cp-XrU59e1RoG-TL7AXz9U
 
