### get root

GET http://localhost:8080

### signin

POST http://localhost:8080/auth  
Content-Type: application/json

{
    "username":"bob",
    "password":"password"
}

### signup

POST http://localhost:8080/signup
Content-Type: application/json

{
    "username":"bob",
    "password":"password" 
}

### show profile

GET http://localhost:8080/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJib2IiLCJpYXQiOjE2OTIxNTE5NTUsImV4cCI6MTY5Mjc1Njc1NX0.dZqYiAf6W1qEq9Z6-5xG3qU-I6HE-Cg5Khg13mBofFw
